- name: Import Common Role where setup tasks present  
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: Import Common Role where Java installation tasks present  
  ansible.builtin.import_role:
    name: common
    tasks_from: java-setup.yaml          #nodejs or nodejs.yaml automatically recognise

- name: Import Common Role for mysql client setup tasks present  
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql-client-setup.yaml

- name: Import Common Role for systemd_service tasks present  
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_service.yaml





