[web]
web.devopswitharun.online
[mongodb]
mongodb.devopswitharun.online
[catalogue]
catalogue.devopswitharun.online
[cart]
cart.devopswitharun.online
[user]
user.devopswitharun.online
[mysql]
mysql.devopswitharun.online
[redis]
redis.devopswitharun.online
[rabbitmq]
rabbitmq.devopswitharun.online
[shipping]
shipping.devopswitharun.online
[payment]
payment.devopswitharun.online
[localhost]
localhost


# [dispatch]
# dispatch.devopswitharun.online

; [all:vars]             #commenting this for we use in group_vars using vault 
; ansible_password=DevOps321 
