- name: Import Common Role where nodejs installation tasks present  
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs          #nodejs or nodejs.yaml automatically recognise

- name: Import Common Role where setup tasks present  
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: Import Common Role for mongodb client setup tasks present  
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb-clent-setup.yaml

- name: Import Common Role for systemd_service tasks present  
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_service.yaml
