[web]
web-dev-dev.devopswitharun.online
[mongodb]
mongodb-dev.devopswitharun.online
[catalogue]
catalogue-dev.devopswitharun.online
[cart]
cart-dev.devopswitharun.online
[user]
user-dev.devopswitharun.online
[mysql]
mysql-dev.devopswitharun.online
[redis]
redis-dev.devopswitharun.online
[rabbitmq]
rabbitmq-dev.devopswitharun.online
[shipping]
shipping-dev.devopswitharun.online
[payment]
payment-dev.devopswitharun.online
[localhost]
localhost


# [dispatch]
# dispatch-dev.devopswitharun.online

; [all:vars]             #commenting this for we use in group_vars using vault 
; ansible_password=DevOps321 
