- name: Configure YUM Repos erlang script for rabbitmq
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Configure YUM Repos for RabbitMQ
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: install rabbitmq
  ansible.builtin.package:
    name: rabbitmq-server
    state: present
  
- name: Start and enable RabbitMQ
  ansible.builtin.service:
    name: rabbitmq-server 
    state: started
    enabled: yes

- name: Read RabbitMQ credentials from SSM Paramaeter Store
  ansible.builtin.set_fact:
    rabbitmq_user: "{{ lookup('aws_ssm', '/roboshop/' ~ env ~ '/rabbitmq_user', region='us-east-1', decrypt=True) }}"
    rabbitmq_password: "{{ lookup('aws_ssm', '/roboshop/' ~ env ~ '/rabbitmq_password', region='us-east-1', decrypt=True) }}"

#for terraform usage 
- name: create username and password for rabbitmq
  community.rabbitmq.rabbitmq_user:
    user: "{{ rabbitmq_user }}"
    password: "{{ rabbitmq_password }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    
    

#/roboshop/dev/rabbitmq_user and /roboshop/dev/rabbitmq_password created manually in ssm parameter store ansible will fetch from there 
# roboshop/dev/rabbitmq_user : roboshop
# /roboshop/dev/rabbitmq_password: roboshop123

 #we used this in ansible    
#  - name: create username and password for rabbitmq
#    ansible.builtin.command: rabbitmqctl add_user {{rq_user}} {{rq_password}}

#  - name: set permission for rabbitmq
#   ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"