[web]
web.-prod.-prod.devopswitharun.online
[mongodb]
mongodb.-prod.devopswitharun.online
[catalogue]
catalogue.-prod.devopswitharun.online
[cart]
cart.-prod.devopswitharun.online
[user]
user.-prod.devopswitharun.online
[mysql]
mysql.-prod.devopswitharun.online
[redis]
redis.-prod.devopswitharun.online
[rabbitmq]
rabbitmq.-prod.devopswitharun.online
[shipping]
shipping.-prod.devopswitharun.online
[payment]
payment.-prod.devopswitharun.online
[localhost]
localhost


# [dispatch]
# dispatch.-prod.devopswitharun.online

; [all:vars]             #commenting this for we use in group_vars using vault 
; ansible_password=DevOps321 
