- name: Copy Mongo repo File 
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB Client
  ansible.builtin.dnf: 
    name: mongodb-org-shell
    state: present

#for catalogue module
- name: Check catalogue entries count
  ansible.builtin.shell: mongo --host {{MONGODB_HOST}} --quiet --eval 'db=db.getSiblingDB("catalogue"); db.products.count()'
  register: products_count
  when: component == "catalogue"

#for user module
- name: Check user entries count
  ansible.builtin.command: mongo --host {{MONGODB_HOST}} --quiet --eval 'db.getSiblingDB("users"); db.users.count()'
  register: users_count
  when: component == "user"

- name: Print catalogue entries count
  ansible.builtin.debug:
    msg: "products_count is : {{products_count}}"
  when: component == "catalogue"

- name: Print user entries count
  ansible.builtin.debug:
    msg: "users_count is : {{users_count}}"
  when: component == "user"

- name: Load catalogue Data to MongoDB
  ansible.builtin.shell: "mongo --host {{MONGODB_HOST}} < /app/schema/catalogue.js"
  when: component == "catalogue" and products_count.stdout == "0"

- name: Load user Data to MongoDB
  ansible.builtin.shell: "mongo --host {{MONGODB_HOST}} < /app/schema/user.js"
  when: component == "user" and users_count.stdout == "0" 